#!/bin/bash
# Script for setting up terminal for SSH sessions

oldterm=$TERM
term="default"
agent=true
addr=""
arg=""
ssh="backpack"

#List of allowed arguments

usage (){
    echo "Usage: $0 [-x] host"
    echo "Options:"
    echo -e "\t-x   set term to xterm"
    echo -e "\t-n   dont save authentication with ssh agent"
    echo -e "\t-a   pass additional argumens to SSH"
    echo -e "\t-t X Y Set up a tunnel between ports local X and remote Y"
    echo -e "\t-s   Use ssh instead of backpack"

    exit 1
}

set_agent (){
    eval $(keychain --eval --quiet --agents ssh id_rsa)>/dev/null
}

#Parse arguments
allowed="xsna:t:"
while getopts $allowed opt; do
    case ${opt} in
        x )
            term=xterm
            ;;
        n )
            agent=false
            ;;

        #Pass additional arguments to SSH (ex: -a "-L 10320:localhost:3200")
        a )
            arg=$OPTARG
            ;;

            #Sets up SSH tunnel from local port X to remote target port Y
            #Usage: -t X:Y 
        t )
            lcl=$(cut -d ":" -f 1 <<< "$OPTARG")
            rmt=$(cut -d ":" -f 2 <<< "$OPTARG")
            arg="-L $lcl:localhost:$rmt"
            ;;
        s )
            ssh="ssh"
            ;;
        h )
            usage
            ;;
        \? )
            usage
            ;;
    esac
done
shift $((OPTIND -1))

if [ ! -n "$1" ]; then
    set_agent
    return 2>/dev/null
    exit
else
    addr=$1
    shift
fi

#Store and forward login credentials
if [ $agent = true ]; then
    #Set up storing of SSH authentication using keychain
    #eval $(keychain --eval --quiet --agents ssh id_rsa)>/dev/null
    set_agent
fi

case ${term} in
    xterm )
        nohup xterm -e $ssh -a $addr &>/dev/null &
        ;;
    default )
        #Change to more recognizeable terminal
        if [ "$TERM" = "rxvt-unicode-256color" ]; then
            TERM="rxvt-unicode"
            export TERM
        fi

        $ssh $arg $addr $@

        #Restore term var after
        TERM=$oldterm
        ;;
esac
