#!/bin/bash

#     Variable declarations
#========================================

_sudo=false
debug=false
prompt=false
tar=true

usage (){
    echo "${0##*/}: Copies a file/directory from a remote server and saves as a tar archive."
    echo "Usage: ${0##*/} host src [dest]"
    echo -e "\t-d\tdebug mode"
    echo -e "\t-s\tRemote sudo mode, prompts for password"
    exit 1
}


#       Parse options
#=======================================

while getopts "hspdn" opt; do
    case $opt in
        h )
            usage
            ;;
        s )
            _sudo=true
            ;;
        d )
            debug=true
            ;;
        p )
            prompt=true
            ;;
        n )
            tar=false
            ;;
        \? )
            usage
            ;;
        : )
            echo "Option requires an argument: $OPTARG"
            exit
            ;;
    esac
done
shift $((OPTIND -1))

if [ "$#" -lt 2 ]; then
    usage
fi

host="$1"
dir=$(dirname "$2")
path=$(basename "$2")
dest="$3"
tarname="$path.grab.tar.gz"
tar_path="/tmp/$tarname"
haul=""

if [ "$prompt" = true ]; then
    read -s -p "Password?
"
fi

if [ "$debug" = false ]; then
    exec 2>/dev/null
fi

cmd="ssh -t $host"
if [ "$_sudo" = true ]; then
    cmd+='echo $pass | sudo -S'
fi

echo "
Smashing"

#If sudo specified, prompt for password
if [ "$_sudo" = true ]; then
    haul=$(ssh -t $host "echo $pass | sudo -S tar -C $dir -cvzaf $tar_path $path | grep -E ^$path; sudo chmod 644 $tar_path && sudo chown \$(whoami) $tar_path") 1>&2
else
    haul=$(ssh -t $host tar -C $dir -cvzaf $tar_path $path | grep -E ^$path; chmod 644 $tar_path) 1>&2
fi

echo "Grabbing"
scp $host:$tar_path .

#If dest provided, move there
if [ ! -z "$dest" ]; then
    mv $tarname $dest
fi

echo "Cleaning up the evidence"
ssh $host rm $tar_path >&2

echo Haul:
echo "$haul"
