#!/bin/bash
#Script for replacing the content of an xml-tag
#Reads from stdin if no file is provided

tag=""
content=""
file=""
str=""
output=""
attribute=""

usage (){
    echo "Usage: $0 tag content [file]"
    exit 1
}

while getopts "a" opt; do
    case $opt in
        a )
            attribute=true
            ;;
        h )
            usage
            ;;
        ? )
            usage
            ;;
        : )
            echo "Option requires an argument: $OPTARG"
            exit 1
            ;;
    esac
done
shift $((OPTIND -1))

tag="$1"
content="$2"

if [ "$attribute" = true ]; then
    attribute="$3"
    shift
fi
file="$3"

if [ $# -lt 2 ]; then
    usage
fi
#Set IFS to avoid consuming whitespace
IFS=
while read line
do
    if [ ! -z "$attribute" ]; then
        #Look for tag, if present then replace attribute with sed
        str=$(grep "<${tag}" <<<$line | sed "s/${content}=\"[^\"]*\"/${content}=\"${attribute}\"/")
        #If no match
        if [ -z "$str" ]; then
            str="$line"
        fi
    else
        str=$(sed "s/<${tag}>.*${tag}>/<${tag}>$content<\/${tag}>/" <<<$line)
    fi
    echo $str 

#Reads from file if defined, otherwise redireects to stdin
done < "${file:-/dev/stdin}"
