#!/bin/bash
#Script for replacing the content of an xml-tag
#Reads from stdin if no file is provided

tag=""
content=""
file=""
str=""
output=""
attribute=""
temp=""

usage (){
    echo "Usage: $0 [-a] tag content [file]"
    echo -e "\t [-a attributeName]\t Edits attribute content instead of regular node content"
    exit 1
}

while getopts "a:" opt; do
    case $opt in
        a )
            attribute="$OPTARG"
            ;;
        h )
            usage
            ;;
        ? )
            usage
            ;;
        : )
            echo "Option requires an argument: $OPTARG"
            exit 1
            ;;
    esac
done
shift $((OPTIND -1))

tag="$1"
content="$2"
file="$3"

if [ $# -lt 2 ]; then
    usage
fi

if [ ! -z "$file" ]; then
    if [ -f "$file" ]; then
        cp "$file" "${file}.tmp"
       temp="${file}.tmp"
    else
        echo "Bad file!"
    fi
fi

#Set IFS to avoid consuming whitespace
IFS=
while read line
do
    if [ ! -z "$attribute" ]; then
        #Look for tag, if present then replace attribute with sed
        str=$(grep "<${tag}" <<<$line | sed "s/${attribute}=\"[^\"]*\"/${attribute}=\"${content}\"/")
        #If no match
        if [ -z "$str" ]; then
            str="$line"
        fi
    else
        str=$(sed "s/<${tag}>.*${tag}>/<${tag}>$content<\/${tag}>/" <<<$line)
    fi
    echo $str 

#Reads from file if defined, otherwise redireects to stdin
done < "${file:-/dev/stdin}"
